### ISSUE TITLE
[Suggestion] Better Config

### ISSUE THREAD

**Issue by BroCrows** [Skintrphoenix/CustomGUI#14]
Config... is garbage! Better revamp it!(Also added some of my suggestions into this)

```
form_name: "Chest"

slot1:
  name: 'Name'
  id: 1
  meta: 0
  count: 1
  lore: 'Description'
  commands:
    - say hi
    - say Add even more commands
  msg: 'You can even attach a message!'
  enchant: true
```
